DiGi/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Be;
using Microsoft.AspNetCore.Hosting;

namespace DiGi.Controllers
{
    public class ProductsController : Controller
    {


        private readonly IWebHostEnvironment Environment;



        public ProductsController(IWebHostEnvironment _environment)
        {

            Environment = _environment;
        }
        BlL.productsBll bl = new BlL.productsBll();





        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Create(Models.ProductsModel h)
        {
            Upload up = new Upload(Environment);

            var newProduct = new Products.Product
            {
                nameProduct = h.nameProduct,

                price = h.price,

                pics = up.Uploadfile(h.pics),

                description = h.description,

                camra = h.camra,

                dimensions = h.dimensions,

                batterySpecifications = h.batterySpecifications,

                bodyStructure = h.bodyStructure,

                introductionTime = h.introductionTime,

                memoryCard = h.memoryCard,

                numberProducts = h.numberProducts,

                operatingSystem = h.operatingSystem,

                productModel = h.productModel,

                screen = h.screen,

                screenSize = h.screenSize,

                specialFeatures = h.specialFeatures,

                weight = h.weight

            };
            bl.Create(newProduct);
            return RedirectToAction("productsPanel", "Admin");
        }
        public IActionResult Search(string h)
        {

            ViewBag.Products = bl.Search(h);

            return View("Views/Admin/productsPanel.cshtml");

        }
        public IActionResult Delete(int id)
        {
            bl.Delete(id);

            return RedirectToAction("productsPanel", "Admin");
        }
        public IActionResult Edit(Models.ProductsModel h)
        {
            var editProd = bl.ReadById(h.id);

            if (editProd != null)
            {
                Upload up = new Upload(Environment);
                var newProd = new Products.Product
                {
                    Id = h.id,
                    nameProduct = h.nameProduct,
                    price = h.price,
                    description = h.description,
                    camra = h.camra,
                    dimensions = h.dimensions,
                    weight = h.weight,
                    screen = h.screen,
                    screenSize = h.screenSize,
                    bodyStructure = h.bodyStructure,
                    specialFeatures = h.specialFeatures,
                    introductionTime = h.introductionTime,
                    productModel = h.productModel,
                    memoryCard = h.memoryCard,
                    numberProducts = h.numberProducts,
                    batterySpecifications = h.batterySpecifications,
                    pics = up.Uploadfile(h.pics),
                    operatingSystem = h.operatingSystem
                };

                bl.EditProducts(newProd);

                return RedirectToAction("productsPanel", "Admin");

            }
            else return RedirectToAction("productsPanel", "Admin");
        }
        public IActionResult ReadByCategory(string h)
        {
            ViewBag.category = h;


            return View();
        }
        public IActionResult ProductDetails(int prodid)
        {
            var prod = bl.ReadById(prodid);
            ViewBag.Prod = prod;

            return View();
        }
        public IActionResult ReadByTCategory(string h)
        {
            ViewBag.Tcategory = h;


            return View("ReadByTcat");
        }

    }

}

DiGi/ViewComponents/products/ProductsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Be;
namespace DiGi.ViewComponents.products
{
    public class ProductsViewComponent :ViewComponent
    {

        public IViewComponentResult Invoke(string Catgory=null)
        {
            Models.ProductsModel h = new Models.ProductsModel();
            h.Catgory = Catgory;
            return View("_products",h);
        }
    }
}

DiGi/ViewComponents/titleCategory/TitleCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DiGi.ViewComponents.titleCategory
{
    public class TitleCategoryViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string Catgory = null)
        {
            Models.ProductsModel h = new Models.ProductsModel();
            h.Catgory = Catgory;
            return View("_titleCategory", h);
        }
    }
}

DiGi/Views/Products/ReadByTcat.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";


    var h = ViewBag.Tcategory;
}
@using Be;
@model ProductsModel






@section link {




    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Font Awesome -->
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <style>
        .Aprod:hover > a {
            background-color: #f79fff;
            color: black
        }
    </style>




}



<div class="content-wrapper">

    <section class="content">



        <div class="col-sm-6">
            <form class="form-inline ml-3" asp-action="Search" asp-controller="Products" method="post">
                <div class="input-group input-group-sm">
                    <input maxlength="25" class="form-control form-control-navbar" name="h" type="search" placeholder="جستجو" aria-label="Search">
                    <div class="input-group-append" style=" background-color: darkgrey;">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div><!-- /.col -->
        <!-- /.card-header -->
        <div class="card" style=" width: 128%; ">



            @await Component.InvokeAsync("TitleCategory", h);

            <!-- /.card-body -->
        </div>
    </section>
</div>

DiGi/Views/Products/readByCategory.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";


    var h = ViewBag.category;
}
@using Be;
@model ProductsModel






@section link {




    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Font Awesome -->
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <style>
        .Aprod:hover > a {
            background-color: #f79fff;
            color: black
        }
    </style>




}



<div class="content-wrapper">

    <section class="content">



        <div class="col-sm-6">
            <form class="form-inline ml-3" asp-action="Search" asp-controller="Products" method="post">
                <div class="input-group input-group-sm">
                    <input maxlength="25" class="form-control form-control-navbar" name="h" type="search" placeholder="جستجو" aria-label="Search">
                    <div class="input-group-append" style=" background-color: darkgrey;">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div><!-- /.col -->
        <!-- /.card-header -->
        <div class="card" style=" width: 128%; ">



            @await Component.InvokeAsync("Products", h);

            <!-- /.card-body -->
        </div>
    </section>
</div>